var formMain = document.getElementById('form_main');
// console.log(t);
var genderList = document.getElementById('gender_list');
// console.log('gender is', genderList);
var firstName = document.getElementById('first_name');
var initialName = document.getElementById('initials_name');
var lastName = document.getElementById('last_name');
var customerAddress = document.getElementById('customer_add');
var customerAddress2 = document.getElementById('customer_add2');
var City = document.getElementById('city_id');
var Region = document.getElementById('region_id');
var postalCode = document.getElementById('postal_id');
var countryPicker = document.getElementById('countryPicker');
var customerNumber = document.getElementById('number_id');
var customerFax = document.getElementById('fax_id');
var calenderDate = document.getElementById('calender_id');
var emailId = document.getElementById('email_id');
var checkBox = document.getElementById('horns');
